@startuml sine

!include ./style.iuml

class Item
class TwoDimensionalItem

class Compartment
class TwoDimensionalCompartment
class Vehicle

class BaseProblem
class Problem
class TwoDimensionalProblem

class LNS
class Solution

' classAlias "multiplicityRole1" o--> "multiplicityRole2" typeAlias : label <<stereotype>> >
' Associations
' Compartment -- Item : compatibility
' Compartment - Item : demand
Item - Compartment: compatibility
Item - Compartment: demand

Vehicle *-- Compartment

BaseProblem o-- Vehicle
BaseProblem o-- Item
' TwoDimensionalProblem o-- TwoDimensionalItem

LNS o-- Problem
LNS o-- Solution

hide empty members
hide @unlinked
@enduml
