@startuml lns_accept

!include ./style.iuml

skinparam linetype ortho

abstract class AcceptanceCriterion {
    apply_acceptance_function(old_solution: Solution,
        \t \t \t \t \t new_solution: Solution, \n  \t \t \t \t \t eval_fun: Callable[[Solution], int])
    update_acceptance_params(...)
}

class SimulatedAnnealing {
    float alpha
    float temperature
    apply_acceptance_function(old_solution: Solution,
        \t \t \t \t \t new_solution: Solution, \n  \t \t \t \t \t eval_fun: Callable[[Solution], int])
    update_acceptance_params(...)
}

left to right direction

'Extensions
AcceptanceCriterion <|-- SimulatedAnnealing

'Hidden links for visualization

hide empty members
@enduml
